version: '2'

networks:
  aspnetcoreapp-network:
    driver: bridge

services:
  nginx:
    container_name: "web_app_nginx"
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aspnetcoreapp-network
    depends_on:
      - "web_app"

  web_app:
    container_name: "web_app"
    build: 
      context: ./src/app/
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/var/www/app
    expose:
      - 5000
    depends_on:
      - "mysql"
    networks:
      - aspnetcoreapp-network
  
  redis:
    container_name: "web_app_redis"
    image: redis:alpine
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    depends_on:
      - "mysql"
    networks:
      - aspnetcoreapp-network
    
  mysql:
    container_name: "web_app_mysql"
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    networks:
      - aspnetcoreapp-network